### ISSUE TITLE
Update to new Ubuntu icon

### ISSUE THREAD

**Issue by igor-cali** [leinardi/UbuntuCountdownWidget#18]
Ubuntu changed logo from 22.04 LTS.
Ref. to this [article](https://www.omgubuntu.co.uk/2022/03/ubuntu-has-a-brand-new-logo).

Thanks!

**Comment by leinardi** [comment]
Hi @igor-cali, thanks for the heads-up, I'll add the new logo with the next release :+1:

**Comment by leinardi** [comment]
Why is the new logo has this tall rectangle :| 
![image](https://user-images.githubusercontent.com/273338/166140967-17b27ea9-681f-4440-804b-bb6239be048e.png)
