### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [leinardi/UbuntuCountdownWidget#22]
```
> Task :build-conventions:jar

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'ubuntucountdownwidget'.
> =============================== Gradle Doctor Prescriptions ============================================
  | JAVA_HOME is not set.                                                                                |
  | Please set JAVA_HOME so that switching between Android Studio and the terminal does not trigger a fu |
  | ll rebuild.                                                                                          |
  | To set JAVA_HOME: (using bash)                                                                       |
  | echo "export JAVA_HOME=$(/usr/libexec/java_home)" >> ~/.bash_profile                                 |
  | or `~/.zshrc` if using zsh.                                                                          |
  |                                                                                                      |
  ========================================================================================================


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

Could you please take a look? Thanks!

**Comment by leinardi** [comment]
Hi @linsui, it seems that the build server does not have `JAVA_HOME` set. Could you please set it?

**Comment by linsui** [comment]
There are Firebase and Google Service in https://github.com/leinardi/UbuntuCountdownWidget/blob/release/build-conventions/build.gradle. Are they added by mistake? Could they be removed?

**Comment by leinardi** [comment]
Oh yeah this was a bad copy paste from another project of mine. Now they are gone (#23).
I don't remember: does F-Droid need a new tag to make a new release or is the updated `version.txt` enough?

**Comment by linsui** [comment]
We can just build it against the new commit. I'll make a MR. Thanks!

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11056

**Comment by leinardi** [comment]
Awesome :+1: 

Feel free to close the issue if everything is fine.

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/2460132837 Any idea? It seems jdk 8 is needed?

**Comment by leinardi** [comment]
The error message is a little strange but I suspect that the issue is setting the `JAVA_HOME` to version 8 instead of version 11:
![image](https://user-images.githubusercontent.com/273338/168544861-3a0ef71f-88d2-49df-8879-681ec9e57f23.png)

Java 11 seems to be already installed so probably it's just about setting the right version for the `JAVA_HOME`:
![image](https://user-images.githubusercontent.com/273338/168545040-1e8ee81d-a499-4c84-8fad-2af8f0f87c93.png)


I use locally and on CI version 11 and it works fine: 
```
$ echo $JAVA_HOME
/usr/lib/jvm/java-11-openjdk-amd64
```

**Comment by leinardi** [comment]
You might also need to update the java alternatives to use java 11 instead of java 8

**Comment by linsui** [comment]
Thanks! Though there is `update-alternatives --auto java` not sure why jdk 8 is used. I set the correct JAVA_HOME and it builds now. But the version is different. Should I just use 291?

**Comment by leinardi** [comment]
Oh I'm sorry I must have messed up the version number. If you can use 291 without any change on my side it would be better for me.

**Comment by linsui** [comment]
Then I just use 291. Thanks!
