### ISSUE TITLE
Wrong version name in version.txt

### ISSUE THREAD

**Issue by linsui** [leinardi/UbuntuCountdownWidget#25]
It should be v23.10.

**Comment by leinardi** [comment]
Hi, thank you for the heads-up, unfortunately I made a mistake with the last release, it is already [fixed on master](https://github.com/leinardi/UbuntuCountdownWidget/blob/709a44a92d1f77c1794cc138df2059af61a5b1bc/version.txt) and on the Play Store.

**Comment by linsui** [comment]
No problem. Just want to make sure it's a mistake. Thanks!

**Comment by leinardi** [comment]
Now should be fixed on the release branch as well. Btw, I'm working on a full rewrite of the widget that will use the [Androidx Glance](https://developer.android.com/jetpack/compose/glance/create-app-widget) library, would you be interested in testing an early version as soon as it's ready?

**Comment by linsui** [comment]
I don't use this app nor ubuntu. But feel free to ping me if you want me to prepare a PR for F-Droid.

**Comment by linsui** [comment]
This time the version code is wrong.

```
2023-09-23 11:32:43,617 ERROR: Could not build app com.leinardi.ubuntucountdownwidget: Unexpected version/version code in output; APK: '2.0.1' / '1695420001',  Expected: '2.0.1' / '1694720001'
```

Could you please take a look?

**Comment by leinardi** [comment]
I think something went wrong with that release, I bumped some deps and made a new one, could you please check if this is fine?
https://github.com/leinardi/UbuntuCountdownWidget/releases/tag/2.0.3

**Comment by linsui** [comment]
It's fine now. Thanks!
