### ISSUE TITLE
No new countdown start with the next version of Ubuntu.

### ISSUE THREAD

**Issue by Maik-aD** [leinardi/UbuntuCountdownWidget#8]
I noticed for a couple of years now that the the widget doesn't start the countdown even though a new version of Ubuntu is on it's way. It did in the past though.
It would be nice if we could see the countdown start automatically once the release schedule of a new Ubuntu version is known and has been released instead of entering the date manually.

**Comment by leinardi** [comment]
Hi @Maik-aD, you are right, this is happening often lately and the only reason is me forgetting to update the release date 😓.
I just released a new version update for Groovy Gorilla (the Play Store is reviewing it currently).

**Comment by Maik-aD** [comment]
Hi @leinardi , thank you for your quick reply and the update. I appreciate it a lot and wish i could help you out so you could release the Ubuntu Countdown widget updates faster and in time. However i don't know how to code or program, maybe i could learn it but don't know where to start. 

All i could do at this point maybe is to send you a reminder whenever the release schedule for the next Ubuntu version has been announced.

**Comment by leinardi** [comment]
Getting a reminder here in the form of a new issue is all I need 👍

**Comment by Maik-aD** [comment]
Then i will keep you informed. Once the release schedule for Ubuntu 21.04 has been announced i will open a new issue.

**Comment by Maik-aD** [comment]
> Hi @Maik-aD, you are right, this is happening often lately and the only reason is me forgetting to update the release date .
> I just released a new version update for Groovy Gorilla (the Play Store is reviewing it currently).
> 
> The APK is also available here: https://github.com/leinardi/UbuntuCountdownWidget/releases/tag/v20.10

Not sure how long it takes but the update still didn't arrive on the Play Store. I downloaded the APK and installed it on one of my devices without a problem and it works.

**Comment by leinardi** [comment]
Unfortunately there seems to be an issue with the Play Store Console: I'm unable to publish the latest update to production. It says that the version code is not valid but I don't get why:

![image](https://user-images.githubusercontent.com/273338/95437805-bba5af80-0955-11eb-9410-c74a3e53147e.png)

It is larger than the previous one (253 > 247). I was able to publish to the open beta tester group (if you join the group you can get it from there on your devices).

I immediately opened a support ticket 4 days ago but still got no answer from Google. Very annoying.

**Comment by Maik-aD** [comment]
Thanks for letting me know @leinardi, i really appreciate it.
What a bummer, that's really annoying what Google is pulling off by not answering. Let's hope it'll turn out fine in the end.
Sure, i'll join the Beta group.

Keep up the good work.
